version: "3"
services:
  app:
    container_name: event_app
    restart: always
    build: ./
    command: nodemon src/server.js
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb://mongo:27017/event_development
  mongo:
    container_name: event_mongo
    image: mongo
    ports:
      - "27017:27017"
  adminmongo:
    container_name: event_mongo_client
    image: "mrvautin/adminmongo"
    ports:
      - 1234:1234
    environment:
      - HOST=0.0.0.0
    depends_on:
      - mongo